### ISSUE TITLE
2 shaarli / 1 yourls

### ISSUE THREAD

**Issue by destef457** [miwasp/yourls-shaarli#1]
Hello,

I have 2 shaarli installations but only one of yourls. 
I would like to be able to shorten the url to the 2 shaarli installations.

I edited the config.php file well. I put a line for the 1st shaarli installation and another for the 2nd. But the second one has no effect.

Is it possible:
- to provide a dialog box allowing you to choose one or the other of the shaarli installations;
- or just a second button?

Thank you for your help,
Sincerely.

Translated with www.DeepL.com/Translator

**Comment by miwasp** [comment]
I think this is a very special use case that nearly nobody needs. I will not add this to the plugin, however you could do the following:

1. Unzip the plugin. You get a "yourls-shaarli" folder
2. Rename this folder to "yourls-shaarli2"
3. Edit the file "plugin.php" inside this folder and replace every "shaarli" with "shaarli2". Do this for all upper, lower and mixed case occurences
4. Upload this folder into the user/plugins folder of your Yourls installation
5. Edit your config.php file (located at user/config.php in your Yourls installation)
6. Define the URL of your second Shaarli installation by inserting the following line at the end of your config.php file. Adapt the URL "https://my-shaarli.com" to your Shaarli installation's URL (No trailing slash !!!), and save changes to config.php

`define('SHAARLI2_URL', 'https://my-shaarli2.com');`

Finally, activate the plugin in the admin area

You should now have two "buttons" to share your links to shaarli.

Below is a diff for the php-script:

```
$ diff plugin.php ../yourls-shaarli/plugin.php
3c3
< Plugin Name: Share to Shaarli2
---
> Plugin Name: Share to Shaarli
14c14
< yourls_add_action( 'share_links', 'jr_yourls_shaarli2' );
---
> yourls_add_action( 'share_links', 'jr_yourls_shaarli' );
16c16
< function jr_yourls_shaarli2( $args ) {
---
> function jr_yourls_shaarli( $args ) {
19,20c19,20
<       if ( defined('SHAARLI2_URL') ) {
<               $shaarli2_url = SHAARLI2_URL;
---
>       if ( defined('SHAARLI_URL') ) {
>               $shaarli_url = SHAARLI_URL;
24c24
<               echo <<<SHAARLI2
---
>               echo <<<SHAARLI
26c26
<               #share_shaarli2{background: transparent url("$icon") left center no-repeat;}
---
>               #share_shaarli{background: transparent url("$icon") left center no-repeat;}
29,32c29,32
<               <a id="share_shaarli2"
<                       href="$shaarli2_url/index.php?post=$longurl&amp;title=$title&amp;source=bookmarklet"
<                       title="Share to Shaarli2"
<                       onclick="yourls_share_on_shaarli2();return false;">Shaarli2
---
>               <a id="share_shaarli"
>                       href="$shaarli_url/index.php?post=$longurl&amp;title=$title&amp;source=bookmarklet"
>                       title="Share to Shaarli"
>                       onclick="yourls_share_on_shaarli();return false;">Shaarli
37,39c37,39
<               function yourls_share_on_shaarli2() {
<                       var url = $('#share_shaarli2').attr('href');
<                       window.open(url, 'shaarli2', 'toolbar=no,width=800,height=600');
---
>               function yourls_share_on_shaarli() {
>                       var url = $('#share_shaarli').attr('href');
>                       window.open(url, 'shaarli', 'toolbar=no,width=800,height=600');
47,48c47,48
<                       var shaarli2 = '$shaarli2_url/index.php?post='+url+'&title='+title+'&source=bookmarklet';
<                       $('#share_shaarli2').attr('href', shaarli2);
---
>                       var shaarli = '$shaarli_url/index.php?post='+url+'&title='+title+'&source=bookmarklet';
>                       $('#share_shaarli').attr('href', shaarli);
52c52
< SHAARLI2;
---
> SHAARLI;

```

**Comment by destef457** [comment]
Hello,
It is true that this should not be a common use.
Thank you very much for your explanations.
It works perfectly.
Have a good evening/day.
